workflows:
  ios-release:
    name: Build & Publish Sanad 2025 iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore_credentials
        - ios_config

    scripts:
      - name: تثبيت الحزم
        script: |
          flutter pub get

      - name: تحديث Flutter و CocoaPods
        script: |
          flutter upgrade
          cd ios
          pod repo update
          pod install
          cd ..

      - name: إنشاء ملف App Store Connect Key من Base64
        script: |
          echo $APP_STORE_CONNECT_PRIVATE_KEY | base64 --decode > AuthKey.p8

      - name: Build iOS Release بدون توقيع محلي
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: AuthKey.p8
        key_id: ${APP_STORE_CONNECT_KEY_IDENTIFIER}
        issuer_id: ${APP_STORE_CONNECT_ISSUER_ID}
