workflows:
  ios-release:
    name: Build & Publish Sanad 2025 iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore_credentials
        - ios_config

   scripts:
  - name: إعادة إنشاء iOS بشكل صحيح
    script: |
      flutter clean
      rm -rf ios
      flutter create .
      flutter pub get

  - name: تثبيت CocoaPods
    script: |
      cd ios
      pod install
      cd ..

  - name: إنشاء ملف App Store Connect Key
    script: |
      echo $APP_STORE_CONNECT_PRIVATE_KEY | base64 --decode > AuthKey.p8

  - name: Build iOS Release
    script: |
      flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: AuthKey.p8
        key_id: ${APP_STORE_CONNECT_KEY_IDENTIFIER}
        issuer_id: ${APP_STORE_CONNECT_ISSUER_ID}
