# Podfile for Flutter project

platform :ios, '12.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Flutter pods
  # استخدم هذا السطر الحديث بدل flutter_install_all_ios_pods
  use_frameworks! # إذا تحتاج
end
