platform :ios, '12.0'

use_frameworks!
use_modular_headers!

# هذا السطر مهم جدًا
require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'))

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
